language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly
        - php: nightly

before_script:
    - composer self-update
    - composer install
